name: code style

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          # Make sure the actual branch is checked out when running on pull requests
          ref: ${{ github.head_ref }}
      - uses: creyD/autopep8_action@v2.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
