name: task watch

on:
  schedule:
    - cron: '*/2 * * * *'
  workflow_dispatch:

jobs:
  watch-task:
    runs-on: ubuntu-latest

    # 実行する処理＆コマンド指定
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v3.1.2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run script
        env:
          NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
          PRIVATE_DB: ${{ secrets.PRIVATE_DB }}
          WORK_DB: ${{ secrets.WORK_DB }}
          SIDEWORK_DB: ${{secrets.SIDEWORK_DB }}
          TZ: "Asia/Tokyo"
        run: |
          python Main.py
